
-- resources
INSERT INTO resources (owner_id, url, thumbnail_img, title, description, category_id) VALUES (1, 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element', 'https://images.pexels.com/photos/18764384/pexels-photo-18764384/free-photo-of-construction-elements-of-a-building-facade.jpeg', 'HTML elements reference', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
INSERT INTO resources (owner_id, url, thumbnail_img, title, description, category_id) VALUES (2, 'https://flexboxfroggy.com/', 'https://images.pexels.com/photos/3726788/pexels-photo-3726788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Flexbox Froggy', 'Nulla tellus cssus.', 2);
INSERT INTO resources (owner_id, url, thumbnail_img, title, description, category_id) VALUES (3, 'https://www.freecodecamp.org/news/what-is-html-definition-and-meaning/', 'https://images.pexels.com/photos/5929346/pexels-photo-5929346.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'What is HTML', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 1);
INSERT INTO resources (owner_id, url, thumbnail_img, title, description, category_id) VALUES (4, 'https://javascript.info/', 'https://images.pexels.com/photos/8798951/pexels-photo-8798951.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Modern Javascript Tutorial', 'Sed ante.', 3);
INSERT INTO resources (owner_id, url, thumbnail_img, title, description, category_id) VALUES (5, 'https://www.simplilearn.com/tutorials/reactjs-tutorial/what-is-reactjs', 'https://images.pexels.com/photos/11159167/pexels-photo-11159167.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'What Is React', 'Curabitur gravida nisi at nibh.', 4);
INSERT INTO resources (owner_id, url, thumbnail_img, title, description, category_id) VALUES (6, 'https://nodejs.dev/en/learn/', 'https://images.pexels.com/photos/18868188/pexels-photo-18868188/free-photo-of-a-woman-in-a-dress-holding-a-book.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Introduction to Node.js', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 5);
INSERT INTO resources (owner_id, url, thumbnail_img, title, description, category_id) VALUES (4, 'https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics', 'https://images.pexels.com/photos/5908639/pexels-photo-5908639.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'JavaScript basics', 'Curabitur gravida nisi at nibh.', 3);
